name: Build APK

on:
  push:
    branches:
      - alpha/add-android-ios-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      KEYSTORE_FILE_NAME: appambit.keystore
      ARTIFACT_NAME: app_appambit_testapp
      APK_PATH: appambit_sdk_react_native/appambit_test_app/android/app/build/outputs/apk/release/app-release.apk
      ROOT_DIR: appambit_sdk_react_native
      TEST_PROJECT_NAME: appambit_test_app
      NODE_VERSION: '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate and extract release type from branch name
        run: |
          FULL_BRANCH="${GITHUB_REF#refs/heads/}"

          if [[ "$FULL_BRANCH" == alpha/* || "$FULL_BRANCH" == beta/* || "$FULL_BRANCH" == production/* ]]; then
            TYPE_RELEASE="${FULL_BRANCH%%/*}"
            echo "TYPE_RELEASE=$TYPE_RELEASE" >> $GITHUB_ENV
          else
            echo "Branch '$FULL_BRANCH' does not start with alpha/, beta/ or production/. Exiting..."
            exit 1
          fi

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create keystore and key.properties
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > ${{ env.KEYSTORE_FILE_NAME }}

          cat <<EOF > key.properties
          keyAlias=${KEY_ALIAS}
          keyPassword=${KEY_PASSWORD}
          storeFile=../${{ env.KEYSTORE_FILE_NAME }}
          storePassword=${KEYSTORE_PASSWORD}
          EOF
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build Release APK
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          ./gradlew assembleRelease

      - name: Locate and rename APK
        run: |
          cd ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
          APK_FILE=$(find . -name "*release*.apk" | head -n 1)
          echo "APK found - $APK_FILE"
          DIR=$(dirname "$APK_FILE")
          NEW_NAME="${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}.apk"
          mv "$APK_FILE" "$DIR/$NEW_NAME"
          echo "APK_PATH=$DIR/$NEW_NAME" >> "$GITHUB_ENV"
          echo "Final APK - $DIR/$NEW_NAME"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}
          path: ${{ env.APK_PATH }}