name: Build APK

on:
  branch:
    - alpha/*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      KEYSTORE_FILE_NAME: appambit.keystore
      ARTIFACT_NAME: app_appambit_testapp
      APK_PATH: appambit_sdk_react_native/appambit_test_app/android/app/build/outputs/apk/release/app-release.apk
      ROOT_DIR: appambit_sdk_react_native
      TEST_PROJECT_NAME: appambit_test_app
      NODE_VERSION: '20'
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate and extract release type from branch name
        run: |
          FULL_BRANCH="${GITHUB_REF#refs/heads/}"

          if [[ "$FULL_BRANCH" == alpha/* || "$FULL_BRANCH" == beta/* || "$FULL_BRANCH" == production/* ]]; then
            TYPE_RELEASE="${FULL_BRANCH%%/*}"
            echo "TYPE_RELEASE=$TYPE_RELEASE" >> $GITHUB_ENV
          else
            echo "Branch '$FULL_BRANCH' does not start with alpha/, beta/ or production/. Exiting..."
            exit 1
          fi

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Node Android dependencies
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          yarn install

      - name: Create keystore
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > ${{ env.KEYSTORE_FILE_NAME }}

      - name: Build Release APK
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          ./gradlew assembleRelease

      - name: Locate and rename APK
        working-directory: ${{ env.ROOT_DIR }}/${{ env.TEST_PROJECT_NAME }}/android
        run: |
          APK_FILE=$(find app/build/outputs/apk/release -name "*release*.apk" | head -n 1)
          echo "APK found - $APK_FILE"
          
          DIR_REL=$(dirname "$APK_FILE")
          DIR_ABS="$(pwd)/$DIR_REL"

          NEW_NAME="${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}.apk"
          mv "$APK_FILE" "$DIR_REL/$NEW_NAME"

          FINAL_APK="$DIR_ABS/$NEW_NAME"
          echo "APK_PATH=$FINAL_APK" >> "$GITHUB_ENV"
          
          echo "Final APK - $FINAL_APK"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_${{ env.TYPE_RELEASE }}
          path: ${{ env.APK_PATH }}